# Generated by Django 5.2.1 on 2025-05-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='industry'),
        ),
    ]
