# Generated by Django 5.2.1 on 2025-05-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_industry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='work_experience',
        ),
        migrations.AddField(
            model_name='user',
            name='work_experience_details',
            field=models.TextField(blank=True, null=True, verbose_name='work experience details'),
        ),
    ]
