# Generated by Django 5.2.1 on 2025-05-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_work_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='work_experience_details',
        ),
        migrations.AddField(
            model_name='user',
            name='work_experience',
            field=models.TextField(blank=True, null=True, verbose_name='work experience'),
        ),
    ]
