# Generated by Django 5.2.1 on 2025-05-16 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_work_experience_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='work_experience',
        ),
    ]
