# Generated by Django 5.2.1 on 2025-05-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_work_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='work_experience_description',
            field=models.TextField(blank=True, null=True, verbose_name='Work Experience Details'),
        ),
    ]
