# Generated by Django 5.2.1 on 2025-05-29 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_user_phone_otp_remove_user_phone_verified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recruiterprofile',
            options={'verbose_name': 'Recruiter Profile', 'verbose_name_plural': 'Recruiter Profiles'},
        ),
    ]
