# Generated by Django 5.1.6 on 2025-12-29 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_recruiterprofile_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecruiterProfile',
        ),
    ]
