# Generated by Django 5.1.6 on 2026-02-09 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_delete_recruiterprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_location',
            field=models.CharField(blank=True, help_text='Primary preferred work location', max_length=255, null=True, verbose_name='preferred location'),
        ),
    ]
