# Generated by Django 5.1.6 on 2026-02-06 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_agent', models.CharField(help_text='Logical name of the sending agent', max_length=100, verbose_name='sender agent')),
                ('receiver_agent', models.CharField(help_text='Logical name of the receiving agent', max_length=100, verbose_name='receiver agent')),
                ('intent', models.CharField(help_text='Action the sender wants the receiver to perform', max_length=200, verbose_name='intent')),
                ('payload', models.JSONField(default=dict, help_text='Structured data attached to the message', verbose_name='payload')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'agent message',
                'verbose_name_plural': 'agent messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentRunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_type', models.CharField(help_text='e.g. career_flow, recruiter_flow, full_multi_agent', max_length=100, verbose_name='run type')),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20, verbose_name='status')),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='result')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('messages', models.ManyToManyField(blank=True, related_name='runs', to='agents.agentmessage', verbose_name='messages')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'agent run log',
                'verbose_name_plural': 'agent run logs',
                'ordering': ['-started_at'],
            },
        ),
    ]
