# Generated by Django 5.2.1 on 2025-05-17 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='job title')),
                ('company', models.CharField(max_length=255, verbose_name='company')),
                ('location', models.CharField(max_length=255, verbose_name='location')),
                ('job_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Internship', 'Internship'), ('Remote', 'Remote'), ('Contract', 'Contract'), ('Freelance', 'Freelance')], max_length=50, verbose_name='job type')),
                ('salary', models.CharField(blank=True, max_length=100, null=True, verbose_name='salary range')),
                ('experience', models.IntegerField(default=0, verbose_name='experience required (years)')),
                ('description', models.TextField(verbose_name='job description')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Paused', 'Paused'), ('Filled', 'Filled')], default='Open', max_length=10, verbose_name='job status')),
                ('skills', models.JSONField(default=list, verbose_name='required skills')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(limit_choices_to={'user_type': 'recruiter'}, on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'job',
                'verbose_name_plural': 'jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected'), ('Interview', 'Interview'), ('Offered', 'Offered'), ('Hired', 'Hired')], default='Applied', max_length=20, verbose_name='application status')),
                ('match_score', models.IntegerField(default=0, verbose_name='match score')),
                ('cover_letter', models.TextField(blank=True, null=True, verbose_name='cover letter')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/', verbose_name='resume')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(limit_choices_to={'user_type__in': ['student', 'professional']}, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruiter.job')),
            ],
            options={
                'verbose_name': 'application',
                'verbose_name_plural': 'applications',
                'ordering': ['-applied_at'],
                'unique_together': {('job', 'applicant')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='subject')),
                ('content', models.TextField(verbose_name='message content')),
                ('is_read', models.BooleanField(default=False, verbose_name='read status')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='recruiter.application')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'ordering': ['-sent_at'],
            },
        ),
    ]
