# Generated by Django 5.1.6 on 2025-08-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='requirements',
            field=models.TextField(blank=True, null=True, verbose_name='job requirements'),
        ),
    ]
