# Generated by Django 5.1.6 on 2025-12-30 14:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        ('recruiter', '0002_job_requirements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSkillRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_proficiency', models.FloatField(default=5.0, help_text='Required skill level (1-10 scale)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='required proficiency level')),
                ('criticality', models.FloatField(default=0.5, help_text='0.0 = nice-to-have, 0.5 = important, 1.0 = must-have', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='criticality')),
                ('is_mandatory', models.BooleanField(default=False, help_text='Whether this skill is absolutely required', verbose_name='mandatory')),
                ('weight', models.FloatField(default=1.0, help_text='Importance multiplier for this skill', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(3.0)], verbose_name='weight')),
                ('years_required', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='years of experience required')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_requirements', to='recruiter.job', verbose_name='job')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_requirements', to='assessments.skill', verbose_name='skill')),
            ],
            options={
                'verbose_name': 'job skill requirement',
                'verbose_name_plural': 'job skill requirements',
                'ordering': ['-criticality', '-required_proficiency'],
                'unique_together': {('job', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='UserJobFitScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField(default=0, help_text='Overall job match percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='overall fit score')),
                ('skill_match_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='skill match score')),
                ('experience_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='experience score')),
                ('matched_skills_count', models.IntegerField(default=0, verbose_name='matched skills')),
                ('total_required_skills', models.IntegerField(default=0, verbose_name='total required skills')),
                ('critical_gaps_count', models.IntegerField(default=0, verbose_name='critical gaps')),
                ('minor_gaps_count', models.IntegerField(default=0, verbose_name='minor gaps')),
                ('strengths_count', models.IntegerField(default=0, verbose_name='strengths')),
                ('is_good_match', models.BooleanField(default=False, verbose_name='good match')),
                ('recommendation', models.TextField(blank=True, help_text='AI-generated recommendation text', verbose_name='recommendation')),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_fit_scores', to='recruiter.job', verbose_name='job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_fit_scores', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user job fit score',
                'verbose_name_plural': 'user job fit scores',
                'ordering': ['-overall_score'],
                'unique_together': {('user', 'job')},
            },
        ),
    ]
