# Generated by Django 5.1.6 on 2025-12-31 13:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0003_jobskillrequirement_userjobfitscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobskillrequirement',
            name='description',
            field=models.TextField(blank=True, help_text='Specific requirements or context for this skill', verbose_name='skill requirement description'),
        ),
        migrations.AddField(
            model_name='jobskillrequirement',
            name='skill_type',
            field=models.CharField(choices=[('must_have', 'Must Have'), ('important', 'Important'), ('nice_to_have', 'Nice to Have')], default='important', help_text='Classification of skill importance', max_length=20, verbose_name='skill type'),
        ),
        migrations.AlterField(
            model_name='jobskillrequirement',
            name='is_mandatory',
            field=models.BooleanField(default=False, help_text='Whether this skill is absolutely required for job eligibility', verbose_name='mandatory'),
        ),
        migrations.AlterField(
            model_name='jobskillrequirement',
            name='required_proficiency',
            field=models.FloatField(default=5.0, help_text='Required skill level (0-10 scale)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='required proficiency level'),
        ),
        migrations.AlterField(
            model_name='jobskillrequirement',
            name='weight',
            field=models.FloatField(default=1.0, help_text='Importance multiplier for matching algorithm', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(3.0)], verbose_name='weight'),
        ),
    ]
