# Generated by Django 5.1.6 on 2026-01-03 07:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('mixed', 'Mixed')], default='mixed', max_length=20, verbose_name='difficulty level')),
                ('duration_minutes', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(180)], verbose_name='duration (minutes)')),
                ('passing_score_percentage', models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='passing score (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'assessment',
                'verbose_name_plural': 'assessments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='skill name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('questions_generated', models.BooleanField(default=False, verbose_name='questions generated')),
                ('questions_generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'skill',
                'verbose_name_plural': 'skills',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='category name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='icon class')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'skill category',
                'verbose_name_plural': 'skill categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='question text')),
                ('question_type', models.CharField(default='mcq', max_length=20, verbose_name='question type')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10, verbose_name='difficulty')),
                ('points', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='points')),
                ('order', models.IntegerField(default=1, verbose_name='order')),
                ('options', models.JSONField(default=list, verbose_name='options')),
                ('correct_answer', models.TextField(verbose_name='correct answer')),
                ('explanation', models.TextField(blank=True, verbose_name='explanation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.assessment', verbose_name='assessment')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
                'ordering': ['assessment', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='question text')),
                ('options', models.JSONField(default=list, help_text='List of answer options (will be shuffled per user)', verbose_name='answer options')),
                ('correct_answer', models.TextField(help_text='Exact text of the correct option', verbose_name='correct answer')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10, verbose_name='difficulty')),
                ('points', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='points')),
                ('explanation', models.TextField(blank=True, verbose_name='explanation')),
                ('times_used', models.IntegerField(default=0, verbose_name='times used')),
                ('times_correct', models.IntegerField(default=0, verbose_name='times correct')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_bank', to='assessments.skill', verbose_name='skill')),
            ],
            options={
                'verbose_name': 'question bank',
                'verbose_name_plural': 'question banks',
                'ordering': ['skill', 'difficulty', '?'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_ids', models.JSONField(default=list, help_text='List of QuestionBank IDs used in this attempt', verbose_name='question IDs')),
                ('shuffled_options', models.JSONField(default=dict, help_text='Mapping of question_id to shuffled options', verbose_name='shuffled options')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20, verbose_name='status')),
                ('score', models.FloatField(default=0, verbose_name='score')),
                ('max_score', models.FloatField(default=0, verbose_name='maximum score')),
                ('percentage', models.FloatField(default=0, verbose_name='percentage')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_seconds', models.IntegerField(default=0, verbose_name='time spent (seconds)')),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessments.assessment', verbose_name='assessment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_attempts', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessments.skill', verbose_name='skill')),
            ],
            options={
                'verbose_name': 'assessment attempt',
                'verbose_name_plural': 'assessment attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='assessment',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='assessments.skill', verbose_name='skill'),
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='assessments.skillcategory', verbose_name='category'),
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.TextField(verbose_name='selected answer')),
                ('is_correct', models.BooleanField(default=False, verbose_name='correct')),
                ('points_earned', models.FloatField(default=0, verbose_name='points earned')),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='assessments.assessmentattempt', verbose_name='attempt')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='assessments.question', verbose_name='question')),
                ('question_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='assessments.questionbank', verbose_name='question')),
            ],
            options={
                'verbose_name': 'user answer',
                'verbose_name_plural': 'user answers',
                'ordering': ['attempt', 'answered_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSkillScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_rated_level', models.FloatField(default=0, help_text="User's self-assessment (0-10)", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='self-rated level')),
                ('verified_level', models.FloatField(default=0, help_text='Verified through assessment (0-10)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='verified level')),
                ('status', models.CharField(choices=[('claimed', 'Claimed (Not Verified)'), ('verified', 'Verified')], default='claimed', max_length=20, verbose_name='status')),
                ('last_assessment_date', models.DateTimeField(blank=True, null=True)),
                ('total_attempts', models.IntegerField(default=0, verbose_name='total attempts')),
                ('best_score_percentage', models.FloatField(default=0, verbose_name='best score (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_assessment_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_scores', to='assessments.assessmentattempt', verbose_name='last attempt')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_scores', to='assessments.skill', verbose_name='skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_scores', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user skill score',
                'verbose_name_plural': 'user skill scores',
                'ordering': ['-verified_level', 'skill'],
            },
        ),
        migrations.CreateModel(
            name='UserSkillProfile',
            fields=[
            ],
            options={
                'verbose_name': 'user skill profile',
                'verbose_name_plural': 'user skill profiles',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('assessments.userskillscore',),
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['skill', 'difficulty'], name='assessments_skill_i_94bb05_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentattempt',
            index=models.Index(fields=['user', 'skill', '-started_at'], name='assessments_user_id_e712de_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentattempt',
            index=models.Index(fields=['status'], name='assessments_status_a61087_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('category', 'name')},
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['attempt', 'question_bank'], name='assessments_attempt_879f25_idx'),
        ),
        migrations.AddIndex(
            model_name='userskillscore',
            index=models.Index(fields=['user', 'status'], name='assessments_user_id_b6ad4d_idx'),
        ),
        migrations.AddIndex(
            model_name='userskillscore',
            index=models.Index(fields=['skill', 'verified_level'], name='assessments_skill_i_ea1d14_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userskillscore',
            unique_together={('user', 'skill')},
        ),
    ]
