# Generated by Django 5.1.6 on 2026-01-06 06:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentattempt',
            name='passed',
            field=models.BooleanField(default=False, verbose_name='passed'),
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='proficiency_level',
            field=models.FloatField(default=0, verbose_name='proficiency level'),
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='selected_question_ids',
            field=models.TextField(default='[]', help_text='JSON string of question IDs (backward compatibility)', verbose_name='selected question IDs'),
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='shuffle_seed',
            field=models.IntegerField(blank=True, help_text='Random seed used for shuffling', null=True, verbose_name='shuffle seed'),
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='total_score',
            field=models.FloatField(default=0, verbose_name='total score'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='created_by_ai',
            field=models.BooleanField(default=False, verbose_name='created by AI'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='proficiency_level',
            field=models.FloatField(default=5.0, help_text='Proficiency level this question tests (0-10)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='proficiency level'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='times_incorrect',
            field=models.IntegerField(default=0, verbose_name='times incorrect'),
        ),
        migrations.AddField(
            model_name='skill',
            name='question_count',
            field=models.IntegerField(default=0, help_text='Number of questions stored in bank (target: 100)', verbose_name='question count'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='ai_evaluation',
            field=models.TextField(blank=True, default='', verbose_name='AI evaluation'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='requires_manual_review',
            field=models.BooleanField(default=False, verbose_name='requires manual review'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='time_taken_seconds',
            field=models.IntegerField(default=0, verbose_name='time taken (seconds)'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='user_answer',
            field=models.JSONField(blank=True, default=dict, verbose_name='user answer'),
        ),
    ]
