# Generated by Django 5.1.6 on 2025-12-29 17:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('course_type', models.CharField(choices=[('video', 'Video Course'), ('interactive', 'Interactive Course'), ('reading', 'Reading Material'), ('project', 'Hands-on Project'), ('workshop', 'Workshop')], default='video', max_length=20, verbose_name='course type')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20, verbose_name='difficulty level')),
                ('platform', models.CharField(choices=[('internal', 'JobElevate'), ('coursera', 'Coursera'), ('udemy', 'Udemy'), ('edx', 'edX'), ('linkedin', 'LinkedIn Learning'), ('youtube', 'YouTube'), ('other', 'Other')], default='internal', max_length=20, verbose_name='platform')),
                ('url', models.URLField(blank=True, max_length=500, validators=[django.core.validators.URLValidator()], verbose_name='course URL')),
                ('duration_hours', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='duration (hours)')),
                ('duration_weeks', models.IntegerField(default=0, help_text='Estimated weeks to complete', verbose_name='duration (weeks)')),
                ('target_proficiency_level', models.FloatField(default=5.0, help_text='Expected proficiency after completion (1-10)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='target proficiency level')),
                ('instructor', models.CharField(blank=True, max_length=255, verbose_name='instructor')),
                ('thumbnail', models.URLField(blank=True, max_length=500, verbose_name='thumbnail URL')),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='rating')),
                ('is_free', models.BooleanField(default=True, verbose_name='free')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='price')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='assessments.skill', verbose_name='skill')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'ordering': ['-rating', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g., 'Python Mastery Path for Data Analyst'", max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('estimated_weeks', models.IntegerField(default=0, help_text='Total time to complete path', verbose_name='estimated weeks')),
                ('estimated_hours', models.FloatField(default=0, verbose_name='estimated hours')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('paused', 'Paused')], default='not_started', max_length=20, verbose_name='status')),
                ('progress_percentage', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='progress (%)')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_paths', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'learning path',
                'verbose_name_plural': 'learning paths',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningPathCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('is_completed', models.BooleanField(default=False, verbose_name='completed')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.course', verbose_name='course')),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.learningpath', verbose_name='learning path')),
            ],
            options={
                'verbose_name': 'learning path course',
                'verbose_name_plural': 'learning path courses',
                'ordering': ['learning_path', 'order'],
                'unique_together': {('learning_path', 'course')},
            },
        ),
        migrations.AddField(
            model_name='learningpath',
            name='courses',
            field=models.ManyToManyField(related_name='learning_paths', through='learning.LearningPathCourse', to='learning.course', verbose_name='courses'),
        ),
        migrations.CreateModel(
            name='SkillGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_level', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='current level')),
                ('required_level', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='required level')),
                ('gap_value', models.FloatField(default=0, help_text='Required - Current', verbose_name='gap value')),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('moderate', 'Moderate'), ('low', 'Low')], default='moderate', max_length=20, verbose_name='priority')),
                ('target_job_title', models.CharField(blank=True, help_text='Job role this gap is identified for', max_length=255, verbose_name='target job title')),
                ('identified_at', models.DateTimeField(auto_now_add=True)),
                ('is_addressed', models.BooleanField(default=False, verbose_name='addressed')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_gaps', to='assessments.skill', verbose_name='skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_gaps', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'skill gap',
                'verbose_name_plural': 'skill gaps',
                'ordering': ['-priority', '-gap_value'],
                'unique_together': {('user', 'skill', 'target_job_title')},
            },
        ),
        migrations.AddField(
            model_name='learningpath',
            name='skill_gap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_paths', to='learning.skillgap', verbose_name='skill gap'),
        ),
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='enrolled', max_length=20, verbose_name='status')),
                ('progress_percentage', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='progress (%)')),
                ('time_spent_hours', models.FloatField(default=0, verbose_name='time spent (hours)')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('certificate_earned', models.BooleanField(default=False, verbose_name='certificate earned')),
                ('certificate_url', models.URLField(blank=True, max_length=500, verbose_name='certificate URL')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='learning.course', verbose_name='course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('learning_path', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_progress', to='learning.learningpath', verbose_name='learning path')),
            ],
            options={
                'verbose_name': 'course progress',
                'verbose_name_plural': 'course progress',
                'ordering': ['-last_accessed_at'],
                'unique_together': {('user', 'course')},
            },
        ),
    ]
