# Generated by Django 5.1.6 on 2025-12-30 14:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
        ('recruiter', '0002_job_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillgap',
            name='estimated_learning_hours',
            field=models.IntegerField(default=0, help_text='Estimated time to close this gap', verbose_name='estimated learning hours'),
        ),
        migrations.AddField(
            model_name='skillgap',
            name='gap_severity',
            field=models.FloatField(default=0, help_text='(Required - Current) / Required', verbose_name='gap severity'),
        ),
        migrations.AddField(
            model_name='skillgap',
            name='job_criticality',
            field=models.FloatField(default=0.5, help_text='0.0 = optional, 1.0 = must-have', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='job criticality'),
        ),
        migrations.AddField(
            model_name='skillgap',
            name='priority_score',
            field=models.FloatField(default=0, help_text='Calculated: (Gap Severity × 0.4) + (Criticality × 0.6)', verbose_name='priority score'),
        ),
        migrations.AddField(
            model_name='skillgap',
            name='related_job',
            field=models.ForeignKey(blank=True, help_text='Specific job posting this gap relates to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_gaps', to='recruiter.job'),
        ),
    ]
