# Generated by Django 5.2.1 on 2025-05-17 15:56

import colorfield.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('preview_image', models.ImageField(upload_to='resume_templates/')),
                ('html_structure', models.TextField()),
                ('css_structure', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('primary_color', colorfield.fields.ColorField(default='#1565C0', image_field=None, max_length=25, samples=None)),
                ('secondary_color', colorfield.fields.ColorField(default='#03A9F4', image_field=None, max_length=25, samples=None)),
                ('font_family', models.CharField(default='Roboto, sans-serif', max_length=100)),
                ('show_contact', models.BooleanField(default=True)),
                ('show_links', models.BooleanField(default=True)),
                ('show_objective', models.BooleanField(default=True)),
                ('show_education', models.BooleanField(default=True)),
                ('show_skills', models.BooleanField(default=True)),
                ('show_experience', models.BooleanField(default=True)),
                ('show_projects', models.BooleanField(default=True)),
                ('show_certifications', models.BooleanField(default=True)),
                ('show_achievements', models.BooleanField(default=True)),
                ('show_extracurricular', models.BooleanField(default=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='resume_pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_downloaded', models.DateTimeField(blank=True, null=True)),
                ('download_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_resumes', to='resume_builder.resumetemplate')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
