# Generated by Django 5.1.6 on 2026-02-09 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0004_jobskillrequirement_description_and_more'),
        ('resume_builder', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TailoredResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('analyzing', 'AI Analyzing'), ('reviewed', 'Suggestions Ready'), ('applied', 'Suggestions Applied'), ('submitted', 'Application Submitted')], default='analyzing', max_length=20)),
                ('suggestions', models.JSONField(blank=True, default=list)),
                ('tailored_objective', models.TextField(blank=True, null=True)),
                ('tailored_skills', models.JSONField(blank=True, default=list, help_text='Skills list after AI tailoring')),
                ('tailored_experience', models.JSONField(blank=True, default=list, help_text='Work experience bullet points after tailoring')),
                ('tailored_projects', models.JSONField(blank=True, default=list, help_text='Projects list after tailoring')),
                ('match_score_before', models.IntegerField(default=0, help_text='Match % before tailoring')),
                ('match_score_after', models.IntegerField(default=0, help_text='Match % after applying suggestions')),
                ('keywords_matched', models.JSONField(blank=True, default=list, help_text='Keywords from job found in tailored resume')),
                ('keywords_missing', models.JSONField(blank=True, default=list, help_text='Job keywords still missing after tailoring')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tailored_versions', to='resume_builder.resume')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tailored_resumes', to='recruiter.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tailored_resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'job', 'base_resume')},
            },
        ),
    ]
