# Generated by Django 6.0.2 on 2026-03-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0002_tailoredresume'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailoredresume',
            name='selected_certifications',
            field=models.JSONField(blank=True, default=None, help_text='Indices of certifications to include (null = all)', null=True),
        ),
        migrations.AddField(
            model_name='tailoredresume',
            name='selected_experience',
            field=models.JSONField(blank=True, default=None, help_text='Indices of work-experience entries to include (null = all)', null=True),
        ),
        migrations.AddField(
            model_name='tailoredresume',
            name='selected_internships',
            field=models.JSONField(blank=True, default=None, help_text='Indices of internships to include (null = all)', null=True),
        ),
        migrations.AddField(
            model_name='tailoredresume',
            name='selected_projects',
            field=models.JSONField(blank=True, default=None, help_text='Indices of projects to include in this tailored resume (null = all)', null=True),
        ),
        migrations.AddField(
            model_name='tailoredresume',
            name='selected_skills',
            field=models.JSONField(blank=True, default=None, help_text='Skill names to include (null = all)', null=True),
        ),
    ]
