# Generated by Django 6.0.2 on 2026-03-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0003_tailored_resume_section_selections'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='selected_certifications',
            field=models.JSONField(blank=True, default=None, help_text='Indices of certifications to include (null = all)', null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='selected_experience',
            field=models.JSONField(blank=True, default=None, help_text='Indices of work-experience entries to include (null = all)', null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='selected_internships',
            field=models.JSONField(blank=True, default=None, help_text='Indices of internships to include (null = all)', null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='selected_projects',
            field=models.JSONField(blank=True, default=None, help_text='Indices of projects to include (null = all)', null=True),
        ),
    ]
