# Generated by Django 5.1.6 on 2026-02-09 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userjobpreference',
            name='experience_level',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='experience level'),
        ),
        migrations.AddField(
            model_name='userjobpreference',
            name='max_salary_expectation',
            field=models.IntegerField(blank=True, null=True, verbose_name='maximum salary expectation'),
        ),
        migrations.AddField(
            model_name='userjobpreference',
            name='salary_currency',
            field=models.CharField(choices=[('INR', '₹ INR - Indian Rupee'), ('USD', '$ USD - US Dollar'), ('EUR', '€ EUR - Euro'), ('GBP', '£ GBP - British Pound'), ('AUD', 'A$ AUD - Australian Dollar'), ('CAD', 'C$ CAD - Canadian Dollar'), ('SGD', 'S$ SGD - Singapore Dollar'), ('AED', 'د.إ AED - UAE Dirham'), ('JPY', '¥ JPY - Japanese Yen')], default='INR', max_length=5, verbose_name='salary currency'),
        ),
        migrations.AddField(
            model_name='userjobpreference',
            name='salary_period',
            field=models.CharField(choices=[('yearly', 'Per Year'), ('monthly', 'Per Month')], default='yearly', max_length=10, verbose_name='salary period'),
        ),
    ]
