"""
Populate Course table with curated learning resources for all active skills.
Run:  python manage.py populate_courses
"""
from django.core.management.base import BaseCommand
from assessments.models import Skill
from learning.models import Course


# Curated courses per skill (keyed by lowercase skill name)
COURSE_DATA = {
    "python": [
        {
            "title": "Python for Everybody",
            "description": "Learn Python fundamentals including variables, loops, functions, and data structures. Perfect for absolute beginners.",
            "difficulty_level": "beginner",
            "platform": "coursera",
            "url": "https://www.coursera.org/specializations/python",
            "duration_hours": 30,
            "duration_weeks": 8,
            "instructor": "Dr. Charles Severance",
            "rating": 4.8,
            "is_free": True,
            "target_proficiency_level": 4.0,
        },
        {
            "title": "Intermediate Python Programming",
            "description": "Master OOP, decorators, generators, context managers, and Pythonic patterns.",
            "difficulty_level": "intermediate",
            "platform": "udemy",
            "url": "https://www.udemy.com/course/python-intermediate/",
            "duration_hours": 25,
            "duration_weeks": 5,
            "instructor": "Fred Baptiste",
            "rating": 4.7,
            "is_free": False,
            "price": 12.99,
            "target_proficiency_level": 7.0,
        },
        {
            "title": "Advanced Python – Concurrency & Performance",
            "description": "Async/await, multiprocessing, C extensions, profiling and optimization techniques.",
            "difficulty_level": "advanced",
            "platform": "linkedin",
            "url": "https://www.linkedin.com/learning/advanced-python",
            "duration_hours": 20,
            "duration_weeks": 4,
            "instructor": "Joe Marini",
            "rating": 4.6,
            "is_free": False,
            "price": 29.99,
            "target_proficiency_level": 9.0,
        },
    ],
    "java": [
        {
            "title": "Java Programming Masterclass",
            "description": "Complete Java course covering basics to advanced topics including collections, streams, and multithreading.",
            "difficulty_level": "beginner",
            "platform": "udemy",
            "url": "https://www.udemy.com/course/java-the-complete-java-developer-course/",
            "duration_hours": 40,
            "duration_weeks": 10,
            "instructor": "Tim Buchalka",
            "rating": 4.6,
            "is_free": False,
            "price": 14.99,
            "target_proficiency_level": 4.0,
        },
        {
            "title": "Java Design Patterns & SOLID Principles",
            "description": "Learn industry-standard design patterns and write clean, maintainable Java code.",
            "difficulty_level": "intermediate",
            "platform": "coursera",
            "url": "https://www.coursera.org/learn/design-patterns",
            "duration_hours": 20,
            "duration_weeks": 4,
            "instructor": "University of Alberta",
            "rating": 4.5,
            "is_free": True,
            "target_proficiency_level": 7.0,
        },
        {
            "title": "Java Microservices with Spring Boot",
            "description": "Build production-ready microservices using Spring Boot, Docker, and Kubernetes.",
            "difficulty_level": "advanced",
            "platform": "udemy",
            "url": "https://www.udemy.com/course/microservices-with-spring-boot/",
            "duration_hours": 30,
            "duration_weeks": 6,
            "instructor": "Ranga Karanam",
            "rating": 4.7,
            "is_free": False,
            "price": 14.99,
            "target_proficiency_level": 9.0,
        },
    ],
    "javascript": [
        {
            "title": "The Complete JavaScript Course",
            "description": "From zero to expert! Learn modern JS with projects, challenges, and real-world scenarios.",
            "difficulty_level": "beginner",
            "platform": "udemy",
            "url": "https://www.udemy.com/course/the-complete-javascript-course/",
            "duration_hours": 35,
            "duration_weeks": 8,
            "instructor": "Jonas Schmedtmann",
            "rating": 4.8,
            "is_free": False,
            "price": 12.99,
            "target_proficiency_level": 4.0,
        },
        {
            "title": "JavaScript: The Hard Parts",
            "description": "Deep-dive into closures, async JS, prototypes, and the event loop.",
            "difficulty_level": "intermediate",
            "platform": "youtube",
            "url": "https://frontendmasters.com/courses/javascript-hard-parts-v2/",
            "duration_hours": 12,
            "duration_weeks": 3,
            "instructor": "Will Sentance",
            "rating": 4.9,
            "is_free": True,
            "target_proficiency_level": 7.0,
        },
        {
            "title": "Advanced JS Patterns & Performance",
            "description": "Master advanced patterns, memory management, and high-performance JavaScript.",
            "difficulty_level": "advanced",
            "platform": "linkedin",
            "url": "https://www.linkedin.com/learning/javascript-patterns",
            "duration_hours": 15,
            "duration_weeks": 3,
            "instructor": "Shaun Wassell",
            "rating": 4.5,
            "is_free": False,
            "price": 29.99,
            "target_proficiency_level": 9.0,
        },
    ],
    "django": [
        {
            "title": "Django for Beginners",
            "description": "Build web applications with Django. Covers models, views, templates, forms, and authentication.",
            "difficulty_level": "beginner",
            "platform": "udemy",
            "url": "https://www.udemy.com/course/django-python/",
            "duration_hours": 20,
            "duration_weeks": 5,
            "instructor": "Jose Portilla",
            "rating": 4.6,
            "is_free": False,
            "price": 12.99,
            "target_proficiency_level": 4.0,
        },
        {
            "title": "Django REST Framework – Build APIs",
            "description": "Create robust REST APIs with DRF, authentication, permissions, and testing.",
            "difficulty_level": "intermediate",
            "platform": "coursera",
            "url": "https://www.coursera.org/learn/django-rest-framework",
            "duration_hours": 18,
            "duration_weeks": 4,
            "instructor": "Meta",
            "rating": 4.5,
            "is_free": True,
            "target_proficiency_level": 7.0,
        },
        {
            "title": "Advanced Django – Scalable Applications",
            "description": "Caching, Celery, signals, custom middleware, deployment, and performance tuning.",
            "difficulty_level": "advanced",
            "platform": "linkedin",
            "url": "https://www.linkedin.com/learning/advanced-django",
            "duration_hours": 15,
            "duration_weeks": 3,
            "instructor": "Leticia Portella",
            "rating": 4.4,
            "is_free": False,
            "price": 29.99,
            "target_proficiency_level": 9.0,
        },
    ],
    "react": [
        {
            "title": "React – The Complete Guide",
            "description": "Learn React from scratch – JSX, components, hooks, context, and Redux.",
            "difficulty_level": "beginner",
            "platform": "udemy",
            "url": "https://www.udemy.com/course/react-the-complete-guide/",
            "duration_hours": 40,
            "duration_weeks": 8,
            "instructor": "Maximilian Schwarzmüller",
            "rating": 4.7,
            "is_free": False,
            "price": 12.99,
            "target_proficiency_level": 4.0,
        },
        {
            "title": "Advanced React Patterns",
            "description": "Compound components, render props, custom hooks, performance optimization.",
            "difficulty_level": "intermediate",
            "platform": "youtube",
            "url": "https://epicreact.dev/",
            "duration_hours": 20,
            "duration_weeks": 4,
            "instructor": "Kent C. Dodds",
            "rating": 4.9,
            "is_free": True,
            "target_proficiency_level": 7.0,
        },
        {
            "title": "React Performance & Architecture",
            "description": "Server components, suspense, concurrent features, and large-scale architecture.",
            "difficulty_level": "advanced",
            "platform": "linkedin",
            "url": "https://www.linkedin.com/learning/react-advanced",
            "duration_hours": 12,
            "duration_weeks": 3,
            "instructor": "Eve Porcello",
            "rating": 4.5,
            "is_free": False,
            "price": 29.99,
            "target_proficiency_level": 9.0,
        },
    ],
    "node.js": [
        {
            "title": "The Complete Node.js Developer Course",
            "description": "Build, test, and deploy Node apps. Express, MongoDB, REST APIs, and more.",
            "difficulty_level": "beginner",
            "platform": "udemy",
            "url": "https://www.udemy.com/course/the-complete-nodejs-developer-course/",
            "duration_hours": 35,
            "duration_weeks": 8,
            "instructor": "Andrew Mead",
            "rating": 4.7,
            "is_free": False,
            "price": 12.99,
            "target_proficiency_level": 4.0,
        },
        {
            "title": "Node.js Design Patterns",
            "description": "Streams, event-driven architecture, microservices patterns in Node.",
            "difficulty_level": "intermediate",
            "platform": "coursera",
            "url": "https://www.coursera.org/learn/server-side-nodejs",
            "duration_hours": 15,
            "duration_weeks": 4,
            "instructor": "Jogesh K. Muppala",
            "rating": 4.5,
            "is_free": True,
            "target_proficiency_level": 7.0,
        },
    ],
    "mongodb": [
        {
            "title": "MongoDB University – M001 Basics",
            "description": "Official MongoDB course covering CRUD, aggregation, indexing, and Atlas.",
            "difficulty_level": "beginner",
            "platform": "other",
            "url": "https://university.mongodb.com/",
            "duration_hours": 15,
            "duration_weeks": 4,
            "instructor": "MongoDB University",
            "rating": 4.6,
            "is_free": True,
            "target_proficiency_level": 4.0,
        },
        {
            "title": "MongoDB Performance & Schema Design",
            "description": "Advanced indexing, sharding, replication, and schema design patterns.",
            "difficulty_level": "intermediate",
            "platform": "other",
            "url": "https://university.mongodb.com/courses/M201/about",
            "duration_hours": 12,
            "duration_weeks": 3,
            "instructor": "MongoDB University",
            "rating": 4.5,
            "is_free": True,
            "target_proficiency_level": 7.0,
        },
    ],
    "machine learning": [
        {
            "title": "Machine Learning by Andrew Ng",
            "description": "The gold-standard ML course covering supervised, unsupervised learning, and neural networks.",
            "difficulty_level": "beginner",
            "platform": "coursera",
            "url": "https://www.coursera.org/learn/machine-learning",
            "duration_hours": 55,
            "duration_weeks": 11,
            "instructor": "Andrew Ng",
            "rating": 4.9,
            "is_free": True,
            "target_proficiency_level": 5.0,
        },
        {
            "title": "Hands-On ML with Scikit-Learn & TensorFlow",
            "description": "Practical ML with real-world projects using scikit-learn, Keras, and TensorFlow.",
            "difficulty_level": "intermediate",
            "platform": "udemy",
            "url": "https://www.udemy.com/course/machinelearning/",
            "duration_hours": 40,
            "duration_weeks": 8,
            "instructor": "Kirill Eremenko",
            "rating": 4.6,
            "is_free": False,
            "price": 14.99,
            "target_proficiency_level": 7.0,
        },
        {
            "title": "Advanced ML – Deep Learning Specialization",
            "description": "CNNs, RNNs, transformers, GANs, and cutting-edge deep learning research.",
            "difficulty_level": "advanced",
            "platform": "coursera",
            "url": "https://www.coursera.org/specializations/deep-learning",
            "duration_hours": 60,
            "duration_weeks": 16,
            "instructor": "Andrew Ng",
            "rating": 4.9,
            "is_free": True,
            "target_proficiency_level": 9.0,
        },
    ],
    "tensorflow": [
        {
            "title": "Intro to TensorFlow for AI & ML",
            "description": "Build and train neural networks with TensorFlow and Keras from scratch.",
            "difficulty_level": "beginner",
            "platform": "coursera",
            "url": "https://www.coursera.org/learn/introduction-tensorflow",
            "duration_hours": 20,
            "duration_weeks": 4,
            "instructor": "Laurence Moroney",
            "rating": 4.7,
            "is_free": True,
            "target_proficiency_level": 4.0,
        },
        {
            "title": "TensorFlow Developer Certificate Prep",
            "description": "Image classification, NLP, time series, and deployment with TensorFlow.",
            "difficulty_level": "intermediate",
            "platform": "coursera",
            "url": "https://www.coursera.org/professional-certificates/tensorflow-in-practice",
            "duration_hours": 30,
            "duration_weeks": 8,
            "instructor": "Laurence Moroney",
            "rating": 4.7,
            "is_free": True,
            "target_proficiency_level": 7.0,
        },
    ],
    "docker": [
        {
            "title": "Docker & Kubernetes: The Practical Guide",
            "description": "Learn Docker from basics to multi-container orchestration with Docker Compose.",
            "difficulty_level": "beginner",
            "platform": "udemy",
            "url": "https://www.udemy.com/course/docker-kubernetes-the-practical-guide/",
            "duration_hours": 23,
            "duration_weeks": 5,
            "instructor": "Maximilian Schwarzmüller",
            "rating": 4.7,
            "is_free": False,
            "price": 12.99,
            "target_proficiency_level": 4.0,
        },
        {
            "title": "Docker Deep Dive – Advanced Techniques",
            "description": "Networking, volumes, security, multi-stage builds, and CI/CD integration.",
            "difficulty_level": "intermediate",
            "platform": "linkedin",
            "url": "https://www.linkedin.com/learning/docker-advanced",
            "duration_hours": 12,
            "duration_weeks": 3,
            "instructor": "Nigel Poulton",
            "rating": 4.6,
            "is_free": False,
            "price": 29.99,
            "target_proficiency_level": 7.0,
        },
    ],
    "kubernetes": [
        {
            "title": "Kubernetes for Absolute Beginners",
            "description": "Pods, deployments, services, and kubectl from scratch with hands-on labs.",
            "difficulty_level": "beginner",
            "platform": "udemy",
            "url": "https://www.udemy.com/course/learn-kubernetes/",
            "duration_hours": 10,
            "duration_weeks": 3,
            "instructor": "Mumshad Mannambeth",
            "rating": 4.7,
            "is_free": False,
            "price": 12.99,
            "target_proficiency_level": 4.0,
        },
        {
            "title": "Certified Kubernetes Administrator (CKA) Prep",
            "description": "Complete CKA exam preparation with cluster management and troubleshooting.",
            "difficulty_level": "advanced",
            "platform": "udemy",
            "url": "https://www.udemy.com/course/certified-kubernetes-administrator/",
            "duration_hours": 25,
            "duration_weeks": 6,
            "instructor": "Mumshad Mannambeth",
            "rating": 4.8,
            "is_free": False,
            "price": 14.99,
            "target_proficiency_level": 9.0,
        },
    ],
    "excel": [
        {
            "title": "Excel Skills for Business",
            "description": "From basic formulas to pivot tables, VLOOKUP, and dashboards.",
            "difficulty_level": "beginner",
            "platform": "coursera",
            "url": "https://www.coursera.org/specializations/excel",
            "duration_hours": 20,
            "duration_weeks": 6,
            "instructor": "Macquarie University",
            "rating": 4.8,
            "is_free": True,
            "target_proficiency_level": 5.0,
        },
        {
            "title": "Advanced Excel – VBA & Macros",
            "description": "Automate workflows, write VBA macros, and build complex financial models.",
            "difficulty_level": "advanced",
            "platform": "udemy",
            "url": "https://www.udemy.com/course/excel-vba/",
            "duration_hours": 15,
            "duration_weeks": 4,
            "instructor": "Kyle Pew",
            "rating": 4.6,
            "is_free": False,
            "price": 12.99,
            "target_proficiency_level": 9.0,
        },
    ],
    "tableau": [
        {
            "title": "Tableau A-Z: Data Visualization",
            "description": "Create interactive dashboards and tell data stories with Tableau.",
            "difficulty_level": "beginner",
            "platform": "udemy",
            "url": "https://www.udemy.com/course/tableau10/",
            "duration_hours": 20,
            "duration_weeks": 5,
            "instructor": "Kirill Eremenko",
            "rating": 4.6,
            "is_free": False,
            "price": 12.99,
            "target_proficiency_level": 5.0,
        },
        {
            "title": "Advanced Tableau – LOD & Calculations",
            "description": "Level of Detail expressions, table calculations, and advanced analytics.",
            "difficulty_level": "advanced",
            "platform": "coursera",
            "url": "https://www.coursera.org/learn/analytics-tableau",
            "duration_hours": 15,
            "duration_weeks": 4,
            "instructor": "UC Davis",
            "rating": 4.5,
            "is_free": True,
            "target_proficiency_level": 8.0,
        },
    ],
    "power-bi": [
        {
            "title": "Microsoft Power BI – From Beginner to Pro",
            "description": "Build interactive reports, DAX formulas, and data models with Power BI.",
            "difficulty_level": "beginner",
            "platform": "udemy",
            "url": "https://www.udemy.com/course/microsoft-power-bi/",
            "duration_hours": 18,
            "duration_weeks": 4,
            "instructor": "Maven Analytics",
            "rating": 4.7,
            "is_free": False,
            "price": 12.99,
            "target_proficiency_level": 5.0,
        },
        {
            "title": "Advanced DAX & Power BI Modeling",
            "description": "Master DAX, relationship modeling, and enterprise deployment of Power BI.",
            "difficulty_level": "advanced",
            "platform": "linkedin",
            "url": "https://www.linkedin.com/learning/power-bi-advanced",
            "duration_hours": 10,
            "duration_weeks": 3,
            "instructor": "Ghassan Karam",
            "rating": 4.5,
            "is_free": False,
            "price": 29.99,
            "target_proficiency_level": 8.0,
        },
    ],
    "flask": [
        {
            "title": "REST APIs with Flask and Python",
            "description": "Build REST APIs from scratch using Flask, SQLAlchemy, and JWT authentication.",
            "difficulty_level": "beginner",
            "platform": "udemy",
            "url": "https://www.udemy.com/course/rest-api-flask-and-python/",
            "duration_hours": 17,
            "duration_weeks": 4,
            "instructor": "Jose Salvatierra",
            "rating": 4.6,
            "is_free": False,
            "price": 12.99,
            "target_proficiency_level": 5.0,
        },
        {
            "title": "Advanced Flask – Production Patterns",
            "description": "Blueprints, Celery, testing, deployment, and application factories.",
            "difficulty_level": "intermediate",
            "platform": "youtube",
            "url": "https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-i-hello-world",
            "duration_hours": 20,
            "duration_weeks": 5,
            "instructor": "Miguel Grinberg",
            "rating": 4.8,
            "is_free": True,
            "target_proficiency_level": 7.0,
        },
    ],
    "ruby": [
        {
            "title": "The Complete Ruby on Rails Developer",
            "description": "Learn Ruby and Rails from scratch with real-world projects.",
            "difficulty_level": "beginner",
            "platform": "udemy",
            "url": "https://www.udemy.com/course/the-complete-ruby-on-rails-developer-course/",
            "duration_hours": 40,
            "duration_weeks": 10,
            "instructor": "Rob Percival",
            "rating": 4.5,
            "is_free": False,
            "price": 12.99,
            "target_proficiency_level": 5.0,
        },
    ],
    "c++": [
        {
            "title": "Beginning C++ Programming",
            "description": "Learn C++ from the ground up – pointers, OOP, STL, and memory management.",
            "difficulty_level": "beginner",
            "platform": "udemy",
            "url": "https://www.udemy.com/course/beginning-c-plus-plus-programming/",
            "duration_hours": 40,
            "duration_weeks": 10,
            "instructor": "Tim Buchalka",
            "rating": 4.6,
            "is_free": False,
            "price": 12.99,
            "target_proficiency_level": 5.0,
        },
        {
            "title": "Advanced C++ – Modern C++20 Features",
            "description": "Concepts, ranges, coroutines, modules, and template metaprogramming.",
            "difficulty_level": "advanced",
            "platform": "coursera",
            "url": "https://www.coursera.org/learn/cpp-champs",
            "duration_hours": 25,
            "duration_weeks": 6,
            "instructor": "University of Illinois",
            "rating": 4.5,
            "is_free": True,
            "target_proficiency_level": 8.0,
        },
    ],
    "sql": [
        {
            "title": "The Complete SQL Bootcamp",
            "description": "Learn SQL with PostgreSQL – queries, joins, subqueries, and window functions.",
            "difficulty_level": "beginner",
            "platform": "udemy",
            "url": "https://www.udemy.com/course/the-complete-sql-bootcamp/",
            "duration_hours": 9,
            "duration_weeks": 2,
            "instructor": "Jose Portilla",
            "rating": 4.7,
            "is_free": False,
            "price": 12.99,
            "target_proficiency_level": 5.0,
        },
        {
            "title": "Advanced SQL for Data Scientists",
            "description": "CTEs, recursive queries, optimization, indexing, and query planning.",
            "difficulty_level": "advanced",
            "platform": "coursera",
            "url": "https://www.coursera.org/learn/advanced-sql",
            "duration_hours": 15,
            "duration_weeks": 4,
            "instructor": "UC Davis",
            "rating": 4.5,
            "is_free": True,
            "target_proficiency_level": 8.0,
        },
    ],
    "data analysis": [
        {
            "title": "Google Data Analytics Certificate",
            "description": "Professional certificate covering spreadsheets, SQL, Tableau, and R for data analysis.",
            "difficulty_level": "beginner",
            "platform": "coursera",
            "url": "https://www.coursera.org/professional-certificates/google-data-analytics",
            "duration_hours": 180,
            "duration_weeks": 24,
            "instructor": "Google",
            "rating": 4.8,
            "is_free": True,
            "target_proficiency_level": 5.0,
        },
        {
            "title": "Data Analysis with Python",
            "description": "Pandas, NumPy, Matplotlib, and statistical analysis for real-world datasets.",
            "difficulty_level": "intermediate",
            "platform": "coursera",
            "url": "https://www.coursera.org/learn/data-analysis-with-python",
            "duration_hours": 20,
            "duration_weeks": 5,
            "instructor": "IBM",
            "rating": 4.6,
            "is_free": True,
            "target_proficiency_level": 7.0,
        },
    ],
    "typescript": [
        {
            "title": "Understanding TypeScript",
            "description": "Learn TypeScript fundamentals – types, interfaces, generics, and decorators.",
            "difficulty_level": "beginner",
            "platform": "udemy",
            "url": "https://www.udemy.com/course/understanding-typescript/",
            "duration_hours": 15,
            "duration_weeks": 3,
            "instructor": "Maximilian Schwarzmüller",
            "rating": 4.7,
            "is_free": False,
            "price": 12.99,
            "target_proficiency_level": 5.0,
        },
        {
            "title": "Advanced TypeScript – Type Gymnastics",
            "description": "Conditional types, mapped types, template literals, and library-grade TS patterns.",
            "difficulty_level": "advanced",
            "platform": "youtube",
            "url": "https://www.totaltypescript.com/",
            "duration_hours": 12,
            "duration_weeks": 3,
            "instructor": "Matt Pocock",
            "rating": 4.9,
            "is_free": True,
            "target_proficiency_level": 8.0,
        },
    ],
    "r": [
        {
            "title": "R Programming Fundamentals",
            "description": "Learn R for data manipulation, visualization, and statistical modeling.",
            "difficulty_level": "beginner",
            "platform": "coursera",
            "url": "https://www.coursera.org/learn/r-programming",
            "duration_hours": 20,
            "duration_weeks": 4,
            "instructor": "Johns Hopkins University",
            "rating": 4.5,
            "is_free": True,
            "target_proficiency_level": 5.0,
        },
        {
            "title": "Advanced R – Tidyverse & Shiny",
            "description": "Master the tidyverse ecosystem, build interactive dashboards with Shiny.",
            "difficulty_level": "intermediate",
            "platform": "edx",
            "url": "https://www.edx.org/learn/r-programming",
            "duration_hours": 18,
            "duration_weeks": 4,
            "instructor": "Harvard X",
            "rating": 4.6,
            "is_free": True,
            "target_proficiency_level": 7.0,
        },
    ],
    "angular": [
        {
            "title": "Angular – The Complete Guide",
            "description": "Build reactive web apps with Angular – components, services, routing, and RxJS.",
            "difficulty_level": "beginner",
            "platform": "udemy",
            "url": "https://www.udemy.com/course/the-complete-guide-to-angular-2/",
            "duration_hours": 35,
            "duration_weeks": 8,
            "instructor": "Maximilian Schwarzmüller",
            "rating": 4.6,
            "is_free": False,
            "price": 12.99,
            "target_proficiency_level": 5.0,
        },
        {
            "title": "Angular Advanced – State Management & Testing",
            "description": "NgRx, advanced RxJS, unit testing, E2E testing, and performance optimization.",
            "difficulty_level": "advanced",
            "platform": "linkedin",
            "url": "https://www.linkedin.com/learning/angular-advanced",
            "duration_hours": 15,
            "duration_weeks": 3,
            "instructor": "Derek Peruo",
            "rating": 4.4,
            "is_free": False,
            "price": 29.99,
            "target_proficiency_level": 8.0,
        },
    ],
    "php": [
        {
            "title": "PHP for Beginners – Become a PHP Master",
            "description": "Complete PHP course covering OOP, MVC, MySQL, and Laravel basics.",
            "difficulty_level": "beginner",
            "platform": "udemy",
            "url": "https://www.udemy.com/course/php-for-complete-beginners-includes-msql-object-oriented/",
            "duration_hours": 30,
            "duration_weeks": 7,
            "instructor": "Edwin Diaz",
            "rating": 4.4,
            "is_free": False,
            "price": 12.99,
            "target_proficiency_level": 5.0,
        },
        {
            "title": "Laravel – PHP Framework Mastery",
            "description": "Build production applications with Laravel, Eloquent ORM, and Blade templates.",
            "difficulty_level": "intermediate",
            "platform": "udemy",
            "url": "https://www.udemy.com/course/php-with-laravel-for-beginners/",
            "duration_hours": 25,
            "duration_weeks": 5,
            "instructor": "Edwin Diaz",
            "rating": 4.5,
            "is_free": False,
            "price": 12.99,
            "target_proficiency_level": 7.0,
        },
    ],
    "spark": [
        {
            "title": "Apache Spark with Python – PySpark",
            "description": "Learn big data processing with PySpark – RDDs, DataFrames, and Spark SQL.",
            "difficulty_level": "intermediate",
            "platform": "udemy",
            "url": "https://www.udemy.com/course/spark-and-python-for-big-data-with-pyspark/",
            "duration_hours": 12,
            "duration_weeks": 3,
            "instructor": "Jose Portilla",
            "rating": 4.5,
            "is_free": False,
            "price": 12.99,
            "target_proficiency_level": 6.0,
        },
    ],
    "data modelling": [
        {
            "title": "Database Design & Data Modelling",
            "description": "Learn ER diagrams, normalization, dimensional modeling, and schema design.",
            "difficulty_level": "beginner",
            "platform": "coursera",
            "url": "https://www.coursera.org/learn/database-design",
            "duration_hours": 15,
            "duration_weeks": 4,
            "instructor": "University of Colorado",
            "rating": 4.5,
            "is_free": True,
            "target_proficiency_level": 5.0,
        },
        {
            "title": "Advanced Data Modeling for Analytics",
            "description": "Star/snowflake schemas, data vault, slowly changing dimensions, and data warehousing.",
            "difficulty_level": "intermediate",
            "platform": "edx",
            "url": "https://www.edx.org/learn/data-modeling",
            "duration_hours": 20,
            "duration_weeks": 5,
            "instructor": "Georgia Tech",
            "rating": 4.4,
            "is_free": True,
            "target_proficiency_level": 7.0,
        },
    ],
    "c#": [
        {
            "title": "C# Fundamentals for Absolute Beginners",
            "description": "Learn C# from scratch – syntax, OOP, LINQ, and .NET basics.",
            "difficulty_level": "beginner",
            "platform": "coursera",
            "url": "https://www.coursera.org/learn/csharp-programming",
            "duration_hours": 20,
            "duration_weeks": 5,
            "instructor": "University of Colorado",
            "rating": 4.5,
            "is_free": True,
            "target_proficiency_level": 5.0,
        },
    ],
    "kotlin": [
        {
            "title": "Kotlin for Android Developers",
            "description": "Learn Kotlin programming and build Android apps from scratch.",
            "difficulty_level": "beginner",
            "platform": "udemy",
            "url": "https://www.udemy.com/course/kotlin-android/",
            "duration_hours": 25,
            "duration_weeks": 6,
            "instructor": "Philipp Lackner",
            "rating": 4.7,
            "is_free": False,
            "price": 12.99,
            "target_proficiency_level": 5.0,
        },
    ],
}

# Generic fallback for skills not in the map above
GENERIC_COURSE_TEMPLATE = [
    {
        "title": "{skill} Fundamentals",
        "description": "A comprehensive beginner course to build solid foundations in {skill}.",
        "difficulty_level": "beginner",
        "platform": "coursera",
        "url": "",
        "duration_hours": 20,
        "duration_weeks": 5,
        "instructor": "Various",
        "rating": 4.0,
        "is_free": True,
        "target_proficiency_level": 4.0,
    },
    {
        "title": "Intermediate {skill} – Real-World Applications",
        "description": "Build on your {skill} foundations with intermediate concepts and projects.",
        "difficulty_level": "intermediate",
        "platform": "udemy",
        "url": "",
        "duration_hours": 18,
        "duration_weeks": 4,
        "instructor": "Various",
        "rating": 4.0,
        "is_free": False,
        "price": 12.99,
        "target_proficiency_level": 7.0,
    },
    {
        "title": "Advanced {skill} Mastery",
        "description": "Master advanced {skill} concepts for professional-level proficiency.",
        "difficulty_level": "advanced",
        "platform": "linkedin",
        "url": "",
        "duration_hours": 15,
        "duration_weeks": 3,
        "instructor": "Various",
        "rating": 4.0,
        "is_free": False,
        "price": 29.99,
        "target_proficiency_level": 9.0,
    },
]


class Command(BaseCommand):
    help = "Populate Course table with curated learning resources for all active skills"

    def add_arguments(self, parser):
        parser.add_argument("--clear", action="store_true", help="Delete existing courses first")
        parser.add_argument("--link-paths", action="store_true", help="Also link courses to existing learning paths")

    def handle(self, *args, **options):
        if options["clear"]:
            deleted, _ = Course.objects.all().delete()
            self.stdout.write(self.style.WARNING(f"Deleted {deleted} existing courses"))

        skills = Skill.objects.filter(is_active=True)
        created_count = 0

        for skill in skills:
            key = skill.name.lower().strip()
            # Also try alternate keys
            courses_data = COURSE_DATA.get(key)
            if not courses_data:
                # Try without dashes/spaces
                for k, v in COURSE_DATA.items():
                    if k.replace("-", "").replace(" ", "") == key.replace("-", "").replace(" ", ""):
                        courses_data = v
                        break

            if not courses_data:
                # Use generic template
                courses_data = [
                    {k: (v.replace("{skill}", skill.name) if isinstance(v, str) else v)
                     for k, v in tpl.items()}
                    for tpl in GENERIC_COURSE_TEMPLATE
                ]

            for cdata in courses_data:
                obj, created = Course.objects.get_or_create(
                    title=cdata["title"],
                    skill=skill,
                    defaults={
                        "description": cdata["description"],
                        "difficulty_level": cdata["difficulty_level"],
                        "platform": cdata["platform"],
                        "url": cdata.get("url", ""),
                        "duration_hours": cdata.get("duration_hours", 15),
                        "duration_weeks": cdata.get("duration_weeks", 4),
                        "instructor": cdata.get("instructor", ""),
                        "rating": cdata.get("rating", 4.0),
                        "is_free": cdata.get("is_free", True),
                        "price": cdata.get("price", 0),
                        "target_proficiency_level": cdata.get("target_proficiency_level", 5.0),
                        "course_type": cdata.get("course_type", "video"),
                    },
                )
                if created:
                    created_count += 1
                    self.stdout.write(f"  + {skill.name}: {obj.title}")

        self.stdout.write(self.style.SUCCESS(f"\nCreated {created_count} courses for {skills.count()} skills"))

        if options["link_paths"]:
            self._link_existing_paths()

    def _link_existing_paths(self):
        """Link courses to existing learning paths that have no courses."""
        from django.db.models import Count
        from learning.models import LearningPath, LearningPathCourse

        empty_paths = LearningPath.objects.annotate(
            course_count=Count("learningpathcourse")
        ).filter(course_count=0)

        linked = 0
        for path in empty_paths:
            skill = path.skill_gap.skill
            current_level = path.skill_gap.current_level

            courses = Course.objects.filter(skill=skill, is_active=True).order_by("difficulty_level", "-rating")

            order = 1
            if current_level < 3:
                for c in courses.filter(difficulty_level="beginner")[:2]:
                    LearningPathCourse.objects.get_or_create(
                        learning_path=path, course=c, defaults={"order": order}
                    )
                    order += 1
            if current_level < 6:
                for c in courses.filter(difficulty_level="intermediate")[:2]:
                    LearningPathCourse.objects.get_or_create(
                        learning_path=path, course=c, defaults={"order": order}
                    )
                    order += 1
            if path.skill_gap.required_level >= 7:
                for c in courses.filter(difficulty_level="advanced")[:1]:
                    LearningPathCourse.objects.get_or_create(
                        learning_path=path, course=c, defaults={"order": order}
                    )
                    order += 1

            if order > 1:
                linked += 1
                self.stdout.write(f"  Linked {order - 1} courses to: {path.title}")

        self.stdout.write(self.style.SUCCESS(f"Linked courses to {linked} learning paths"))
